# -*- coding: utf-8 -*-
"""Blogger.ipynbimport

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2kwbOvK9EBTCfiq45iKezCIPfc6ltV4
"""

#pip install google-generativeai

"""
Google Colab Notebook for AI Blogger with Gemini

**Description:**

This notebook demonstrates an AI blogger built with the Gemini library.
It allows you to provide a topic, and the script will generate a blog post based on that topic using Gemini's capabilities.

**Output:**

The script will generate a blog post based on the provided topic and display it within the notebook.
"""

import os


# Add your Gemini API Key Below
genai.configure(api_key='AIzaSyCA3EgC2w414op8DwrtTBcy0sSvoWRvLjs')

# Create the model
# See https://ai.google.dev/api/python/google/generativeai/GenerativeModel
generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 64,
  "max_output_tokens": 8192,
  "response_mime_type": "text/plain",
}

model = genai.GenerativeModel(
  model_name="gemini-flash-latest",
  generation_config=generation_config,
  # safety_settings = Adjust safety settings
  # See https://ai.google.dev/gemini-api/docs/safety-settings
  system_instruction="Act as an experienced blogger who knows about all the topics in this world. You will be receiving a blog post topic as an input and you have to write a crisp and humanly toned blog post. Do not make up fake stuff and try to be very factual and quote stats related to that topic if possible to make the end result accurate. Keep the word count at around 150 words. Do not cross this word limit.",
)

chat_session = model.start_chat(
  history=[
    {
      "role": "user",
      "parts": [
        "Java",
      ],
    },
    {
      "role": "model",
      "parts": [
        "## Java: Still Going Strong After All These Years ☕\n\nJava – the name alone conjures images of coding bootcamps and endless lines of code. But don't let its age fool you, this programming language is far from obsolete. \n\nBorn in 1995, Java's \"write once, run anywhere\" philosophy quickly made it a favorite. Today, it remains incredibly relevant, powering everything from Android apps to enterprise-level systems.  Its stability, vast libraries, and active community make it a top choice for businesses and developers alike.  \n\nDon't just take our word for it – statistics show that Java is consistently ranked among the top 3 most popular programming languages worldwide.  Whether you're a seasoned developer or just starting out, Java's versatility and enduring popularity make it a language worth learning. \n",
      ],
    },
    {
      "role": "user",
      "parts": [
        "Maruti Suzuki Swift",
      ],
    },
    {
      "role": "model",
      "parts": [
        "##  The Maruti Suzuki Swift: India's Constant Companion 🚗\n\nZipping through crowded streets or cruising down highways, the Maruti Suzuki Swift has become a ubiquitous sight in India.  Launched in 2005, its blend of affordability, fuel efficiency, and sporty looks struck a chord with Indian consumers. \n\nOver 2.2 million Swifts have been sold in India, making it one of the country's best-selling cars ever.  Its peppy engine options, easy maneuverability, and low maintenance costs make it a favorite for first-time car buyers and seasoned drivers alike. \n\nThe Swift has evolved through the years, with each iteration refining its design and features.  But its core appeal remains unchanged: a reliable and stylish hatchback that fits perfectly into the Indian automotive landscape.  \n",
      ],
    },
  ]
)

response = chat_session.send_message("Google")

print(response.text)